export const LOAD_POSTS_SUCCESS = 'LOAD_POSTS_SUCCESS';
export const POSTS_LOADING = 'POSTS_LOADING';
export const HOME_LOADING = 'HOME_LOADING';
export const LOAD_HOME_SUCCESS = 'LOAD_HOME_SUCCESS';
